@startuml
!theme C4_brown from <C4/themes>
!include <C4/C4_Context>

Person(client, "Client", "Bank client")
Person(bank_employee, "Employee", "Bank employee")
Person(manager, "Back office manager", "Account Manager")

System(standart_bank, "Standart Bank", "Online banking")

Rel_D(client, standart_bank, "Views deposits info/Creates applications for deposits")
Rel_U(manager, standart_bank, "Gets deposit application info/Accepts or rejects application")
Rel_U(manager, client, "Сonnects about deposit")

Rel_U(bank_employee, standart_bank, "Updates/Reads deposits rate")

System_Ext(telecom_operator, "Telecom Operator", "Sends SMS to clients")

Rel_L(standart_bank, telecom_operator, "SMS send request")
Rel_U(telecom_operator, client, "Sends SMS")

@enduml