@startuml
!theme C4_brown from <C4/themes>
!include <C4/C4_Context>

Person(client, "Клиент", "Клиент банка")
Person(bank_employee, "Сотрудник", "Сотрудник банка")
Person(call_manager, "Менеджер колл центра", "Менеджер по работе с клиентами")
Person(partner_call_manager, "Менеджер партнерского колл центра", "Менеджер по работе с клиентами")

System(standart_bank, "Стандарт Банк", "Интернет-банкинг")

System_Ext(call_center_partner, "Партнерской колл центр", "Система партнерского колл центра")
Rel(partner_call_manager, call_center_partner, "Получает заявки, просматривает информацию о депозитах")
Rel_U(partner_call_manager, client, "Связывается с клиентом")

Rel(call_manager, standart_bank, "Получает новую заявку, просматривает информацию о депозитах")
Rel_U(call_manager, client, "Связывается с клиентом")
Rel_U(bank_employee, standart_bank, "Обновляет/Просматривает ставки по вкладам")

Rel(standart_bank, call_center_partner, "Передает заявки и информацию о депозитах")

@enduml